spring:
 profiles:
  active:
  - dev
---
spring:
 profiles: dev
 application:
  name: microservicecloud-config-tzy-dev
---
spring:
 profiles: test
 application:
  name: microservicecloud-config-tzy-test #请保存为UTF-8格式
