spring:
  profiles:
    active:
    - dev
---
server:
  port:8001
spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01?serverTimezone=GMT%2B8&useSSL=false            # 数据库名称
    username: root
    password: 114114
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.tzy.springcloud.entities    # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: microservicecloud-dept8001 #自定义服务器名称信息
    prefer-ip-address: true  #访问路径可以显示IP地址
info:
  app.name: tzy-microservicecloud
  company.name: www.tzy.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
